-- migrate:up
BEGIN;
create table users (
	user_id 				integer primary key generated by default as identity,
	user_first_name	text not null,
	user_last_name	text not null,
	user_email			text not null
);
COMMIT;
-- migrate:down

