-- migrate:up
BEGIN;

create table anons (
	anon_id integer primary key generated by default as identity
);

create table documents (
	document_id integer primary key generated by default as identity,
	document_name text not null,
	document_created_at timestamp default current_timestamp,

	anon_id integer not null references anons(anon_id) on delete cascade
);

alter table users
	add column document_id integer references documents(document_id) on delete cascade;

ROLLBACK;
-- migrate:down

